// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YudaSPCWebApplication.BackendServer.Data;

#nullable disable

namespace YudaSPCWebApplication.BackendServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251104130817_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("KnowledgeBaseSepence");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.Characteristic", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<bool?>("BoolDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("IntAreaID")
                        .HasColumnType("int");

                    b.Property<int?>("IntCharacteristicType")
                        .HasColumnType("int");

                    b.Property<int?>("IntDecimals")
                        .HasColumnType("int");

                    b.Property<int?>("IntDefectRateLimit")
                        .HasColumnType("int");

                    b.Property<int?>("IntEmailEventModel")
                        .HasColumnType("int");

                    b.Property<int?>("IntEventEnable")
                        .HasColumnType("int");

                    b.Property<int?>("IntMeaTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("IntProcessID")
                        .HasColumnType("int");

                    b.Property<string>("StrCharacteristicName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StrCharacteristicUnit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StrMeaType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrNameArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrProcessName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IntID");

                    b.ToTable("tbBlockVialFixture");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.EmailServer", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<bool?>("BoolEnabledSSL")
                        .HasColumnType("bit");

                    b.Property<int?>("IntSMTPPort")
                        .HasColumnType("int");

                    b.Property<string>("StrDisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrEmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrPassword")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrSMTPHost")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IntID");

                    b.ToTable("tbEmailServer");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.EventLog", b =>
                {
                    b.Property<int>("IntEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntEventID"));

                    b.Property<DateTime?>("DtEventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StrEvent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StrEventCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StrStation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IntEventID");

                    b.ToTable("tbEventLog");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.EventRoles", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<int?>("IntAreaID")
                        .HasColumnType("int");

                    b.Property<int?>("IntCharacteristicID")
                        .HasColumnType("int");

                    b.Property<int?>("IntDefectRateLimit")
                        .HasColumnType("int");

                    b.Property<int?>("IntEmailEventModel")
                        .HasColumnType("int");

                    b.Property<int?>("IntEventEnable")
                        .HasColumnType("int");

                    b.Property<int?>("IntMeaTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("IntProcessID")
                        .HasColumnType("int");

                    b.Property<string>("StrCharacteristicName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StrCharacteristicUnit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrMeaType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrNameArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrProcessName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrRoleID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IntID");

                    b.ToTable("tbEventRoles");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.InspectionPlanType", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<string>("StrPlanTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IntID");

                    b.ToTable("tbInspectionPlanType");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.JobData", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<bool?>("BoolDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DtCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IntAreaID")
                        .HasColumnType("int");

                    b.Property<int?>("IntColorCode")
                        .HasColumnType("int");

                    b.Property<int?>("IntInspPlanID")
                        .HasColumnType("int");

                    b.Property<int?>("IntJobDecisionID")
                        .HasColumnType("int");

                    b.Property<int?>("IntJobQty")
                        .HasColumnType("int");

                    b.Property<int?>("IntOutputQty")
                        .HasColumnType("int");

                    b.Property<int?>("IntProductID")
                        .HasColumnType("int");

                    b.Property<int?>("IntVialFixture")
                        .HasColumnType("int");

                    b.Property<string>("StrDecision")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StrInspPlanName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrJobCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrModelInternal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrNameArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrNameProduct")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrPOCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrSOCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrVialFixture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IntID");

                    b.ToTable("tbJobData");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.JobDecision", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<int>("IntColorCode")
                        .HasColumnType("int");

                    b.Property<string>("StrDecision")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IntID");

                    b.ToTable("tbJobDecision");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.MeasData", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<DateTime?>("DtTimeMeasure")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IntCavityID")
                        .HasColumnType("int");

                    b.Property<int?>("IntCharacteristicID")
                        .HasColumnType("int");

                    b.Property<int?>("IntDataCollection")
                        .HasColumnType("int");

                    b.Property<int?>("IntJobID")
                        .HasColumnType("int");

                    b.Property<int?>("IntLineID")
                        .HasColumnType("int");

                    b.Property<int?>("IntMoldID")
                        .HasColumnType("int");

                    b.Property<int?>("IntOutputQty")
                        .HasColumnType("int");

                    b.Property<int?>("IntProductionID")
                        .HasColumnType("int");

                    b.Property<int?>("IntSampleIndex")
                        .HasColumnType("int");

                    b.Property<int?>("IntSampleQty")
                        .HasColumnType("int");

                    b.Property<int?>("IntUserID")
                        .HasColumnType("int");

                    b.Property<string>("StrFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrOutputNotes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrPlanTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VarCharacteristicRange")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VarCharacteristicValue")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("IntID");

                    b.ToTable("MeasDatas");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.MeasureType", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<string>("StrMeaType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IntID");

                    b.ToTable("tbMeasureType");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.Process", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<int?>("IntAreaID")
                        .HasColumnType("int");

                    b.Property<string>("StrProcessName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IntID");

                    b.ToTable("tbProcess");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.ProcessLine", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<int?>("IntProcessID")
                        .HasColumnType("int");

                    b.Property<string>("StrProcessLineCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrProcessLineName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IntID");

                    b.ToTable("tbProcessLine");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.ProductName", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<bool>("BoolDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("IntAreaID")
                        .HasColumnType("int");

                    b.Property<int?>("IntInspPlanID")
                        .HasColumnType("int");

                    b.Property<int?>("IntVialFixture")
                        .HasColumnType("int");

                    b.Property<string>("StrCustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrModelInternal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrNameProduct")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrNotes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrVialFixture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IntID");

                    b.ToTable("tbProductName");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.ProductionArea", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<string>("StrNameArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IntID");

                    b.ToTable("tbProductionArea");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.ProductionData", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<bool?>("BoolDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DtCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IntAreaID")
                        .HasColumnType("int");

                    b.Property<int?>("IntCNCLatheMachine")
                        .HasColumnType("int");

                    b.Property<int?>("IntInspPlanID")
                        .HasColumnType("int");

                    b.Property<int?>("IntJobID")
                        .HasColumnType("int");

                    b.Property<int?>("IntJobQty")
                        .HasColumnType("int");

                    b.Property<int?>("IntLineID")
                        .HasColumnType("int");

                    b.Property<int?>("IntOutputQty")
                        .HasColumnType("int");

                    b.Property<int?>("IntProcessID")
                        .HasColumnType("int");

                    b.Property<int?>("IntProductID")
                        .HasColumnType("int");

                    b.Property<int?>("IntProductionQty")
                        .HasColumnType("int");

                    b.Property<int?>("IntUserID")
                        .HasColumnType("int");

                    b.Property<int?>("IntVialFixture")
                        .HasColumnType("int");

                    b.Property<string>("StrCNCLatheMachine")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrCustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrInspPlanName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrJobCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrLotInform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrMaterialInform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrModelInternal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrNameArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrNameProduct")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrNotes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrPOCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrProcessLineCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrProcessLineName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrProcessName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrSOCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrVialFixture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IntID");

                    b.ToTable("tbProductionData");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntLevel")
                        .HasColumnType("int");

                    b.Property<int>("IntRoleID")
                        .HasColumnType("int");

                    b.Property<int?>("IntRoleUser")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StrDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StrRoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.Shift", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<TimeSpan?>("DtEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("DtStartTime")
                        .HasColumnType("time");

                    b.Property<string>("StrNameShift")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IntID");

                    b.ToTable("tbShift");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.TVDisplay", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<string>("StrCavityID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrCharacteristicID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrMoldID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrPlanTypeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrProductionID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrTVName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IntID");

                    b.ToTable("tbTVDisplay");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.WebSession", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<DateTime?>("DtEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StrIpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrSessionID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IntID");

                    b.ToTable("tbWebSession");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DtLastActivityTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("IntEnable")
                        .HasColumnType("int");

                    b.Property<int>("IntUserID")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrEmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StrPassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrRoleID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StrSelectedAreaID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrStaffID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
