// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YudaSPCWebApplication.BackendServer.Data;

#nullable disable

namespace YudaSPCWebApplication.BackendServer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251227162452_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("KnowledgeBaseSepence");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.Characteristic", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<bool?>("BoolDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("boolDeleted");

                    b.Property<int?>("IntCharacteristicType")
                        .HasColumnType("int")
                        .HasColumnName("intCharacteristicType");

                    b.Property<int?>("IntDecimals")
                        .HasColumnType("int")
                        .HasColumnName("intDecimals");

                    b.Property<int?>("IntDefectRateLimit")
                        .HasColumnType("int")
                        .HasColumnName("intDefectRateLimit");

                    b.Property<int?>("IntEmailEventModel")
                        .HasColumnType("int")
                        .HasColumnName("intEmailEventModel");

                    b.Property<int?>("IntEventEnable")
                        .HasColumnType("int")
                        .HasColumnName("intEventEnable");

                    b.Property<int?>("IntMeaTypeID")
                        .HasColumnType("int")
                        .HasColumnName("intMeaTypeID");

                    b.Property<int?>("IntProcessID")
                        .HasColumnType("int")
                        .HasColumnName("intProcessID");

                    b.Property<string>("StrCharacteristicName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("strCharacteristicName");

                    b.Property<string>("StrCharacteristicUnit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("strCharacteristicUnit");

                    b.HasKey("IntID");

                    b.ToTable("tbCharacteristic");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.EmailServer", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<bool?>("BoolEnabledSSL")
                        .HasColumnType("bit")
                        .HasColumnName("boolEnabledSSL");

                    b.Property<int?>("IntSMTPPort")
                        .HasColumnType("int")
                        .HasColumnName("intSMTPPort");

                    b.Property<string>("StrDisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strDisplayName");

                    b.Property<string>("StrEmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strEmailAddress");

                    b.Property<string>("StrPassword")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strPassword");

                    b.Property<string>("StrSMTPHost")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strSMTPHost");

                    b.HasKey("IntID");

                    b.ToTable("tbEmailServer");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.EventLog", b =>
                {
                    b.Property<int>("IntEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intEventID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntEventID"));

                    b.Property<DateTime?>("DtEventTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dtEventTime");

                    b.Property<string>("StrEvent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("strEvent");

                    b.Property<string>("StrEventCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("strEventCode");

                    b.Property<string>("StrStation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("strStation");

                    b.HasKey("IntEventID");

                    b.ToTable("tbEventLog");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.EventRoles", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<int?>("IntCharacteristicID")
                        .HasColumnType("int")
                        .HasColumnName("intCharacteristicID");

                    b.Property<string>("StrRoleID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strRoleID");

                    b.HasKey("IntID");

                    b.ToTable("tbEventRoles");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.InspectionPlanType", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<string>("StrPlanTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strPlanTypeName");

                    b.HasKey("IntID");

                    b.ToTable("tbInspectionPlanType");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.JobData", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<bool?>("BoolDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("boolDeleted");

                    b.Property<DateTime?>("DtCreateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dtCreateTime");

                    b.Property<int?>("IntAreaID")
                        .HasColumnType("int")
                        .HasColumnName("intAreaID");

                    b.Property<int?>("IntJobDecisionID")
                        .HasColumnType("int")
                        .HasColumnName("intJobDecisionID");

                    b.Property<int?>("IntJobQty")
                        .HasColumnType("int")
                        .HasColumnName("intJobQty");

                    b.Property<int?>("IntOutputQty")
                        .HasColumnType("int")
                        .HasColumnName("intOutputQty");

                    b.Property<int?>("IntProductID")
                        .HasColumnType("int")
                        .HasColumnName("intProductID");

                    b.Property<int?>("IntUserID")
                        .HasColumnType("int")
                        .HasColumnName("intUserID");

                    b.Property<string>("StrJobCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strJobCode");

                    b.Property<string>("StrPOCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strPOCode");

                    b.Property<string>("StrSOCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strSOCode");

                    b.HasKey("IntID");

                    b.ToTable("tbJobData");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.JobDecision", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<int>("IntColorCode")
                        .HasColumnType("int")
                        .HasColumnName("intColorCode");

                    b.Property<string>("StrDecision")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("strDecision");

                    b.HasKey("IntID");

                    b.ToTable("tbJobDecision");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.MeasData3_01", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<DateTime?>("DtTimeMeasure")
                        .HasColumnType("datetime")
                        .HasColumnName("dtTimeMeasure");

                    b.Property<DateTime?>("DtTimeStamp")
                        .HasColumnType("datetime")
                        .HasColumnName("dtTimeStamp");

                    b.Property<int?>("IntCavityID")
                        .HasColumnType("int")
                        .HasColumnName("intCavityID");

                    b.Property<int?>("IntCharacteristicID")
                        .HasColumnType("int")
                        .HasColumnName("intCharacteristicID");

                    b.Property<int?>("IntDataCollection")
                        .HasColumnType("int")
                        .HasColumnName("intDataCollection");

                    b.Property<int?>("IntEmailSent")
                        .HasColumnType("int")
                        .HasColumnName("intEmailSent");

                    b.Property<int?>("IntJobID")
                        .HasColumnType("int")
                        .HasColumnName("intJobID");

                    b.Property<int?>("IntLineID")
                        .HasColumnType("int")
                        .HasColumnName("intLineID");

                    b.Property<int?>("IntMoldID")
                        .HasColumnType("int")
                        .HasColumnName("intMoldID");

                    b.Property<int?>("IntOKNG")
                        .HasColumnType("int")
                        .HasColumnName("intOKNG");

                    b.Property<int?>("IntOutputQty")
                        .HasColumnType("int")
                        .HasColumnName("intOutputQty");

                    b.Property<int?>("IntPlanTypeID")
                        .HasColumnType("int")
                        .HasColumnName("intPlanTypeID");

                    b.Property<int?>("IntProductionID")
                        .HasColumnType("int")
                        .HasColumnName("intProductionID");

                    b.Property<int?>("IntSampleIndex")
                        .HasColumnType("int")
                        .HasColumnName("intSampleIndex");

                    b.Property<int?>("IntSampleQty")
                        .HasColumnType("int")
                        .HasColumnName("intSampleQty");

                    b.Property<int?>("IntUserID")
                        .HasColumnType("int")
                        .HasColumnName("intUserID");

                    b.Property<string>("StrOutputNotes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strOutputNotes");

                    b.Property<string>("VarCharacteristicRange")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("varCharacteristicRange");

                    b.Property<string>("VarCharacteristicValue")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("varCharacteristicValue");

                    b.HasKey("IntID");

                    b.ToTable("tbMeasData3_01");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.MeasureType", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<string>("StrMeaType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strMeaType");

                    b.HasKey("IntID");

                    b.ToTable("tbMeasureType");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.Process", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<int?>("IntAreaID")
                        .HasColumnType("int")
                        .HasColumnName("intAreaID");

                    b.Property<string>("StrProcessName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strProcessName");

                    b.HasKey("IntID");

                    b.ToTable("tbProcess");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.ProcessLine", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<int?>("IntProcessID")
                        .HasColumnType("int")
                        .HasColumnName("intAreaID");

                    b.Property<string>("StrProcessLineCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strProcessLineCode");

                    b.Property<string>("StrProcessLineName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strProcessLineName");

                    b.HasKey("IntID");

                    b.ToTable("tbProcessLine");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.ProductName", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<bool>("BoolDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("boolDeleted");

                    b.Property<int?>("IntAreaID")
                        .HasColumnType("int")
                        .HasColumnName("intAreaID");

                    b.Property<int?>("IntCavityQty")
                        .HasColumnType("int")
                        .HasColumnName("intCavityQty");

                    b.Property<int?>("IntInspPlanID")
                        .HasColumnType("int")
                        .HasColumnName("intInspPlanID");

                    b.Property<int?>("IntMoldQty")
                        .HasColumnType("int")
                        .HasColumnName("intMoldQty");

                    b.Property<int?>("IntVialFixture")
                        .HasColumnType("int")
                        .HasColumnName("intVialFixture");

                    b.Property<string>("StrCustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strCustomerName");

                    b.Property<string>("StrDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strDescription");

                    b.Property<string>("StrModelInternal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strModelInternal");

                    b.Property<string>("StrNameProduct")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strNameProduct");

                    b.Property<string>("StrNotes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strNotes");

                    b.HasKey("IntID");

                    b.ToTable("tbProductName");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.ProductionArea", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<string>("StrNameArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strNameArea");

                    b.HasKey("IntID");

                    b.ToTable("tbProductionArea");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.ProductionData", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<bool?>("BoolDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("boolDeleted");

                    b.Property<DateTime?>("DtEndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dtEndTime");

                    b.Property<DateTime?>("DtProductionDate")
                        .HasColumnType("datetime")
                        .HasColumnName("dtProductionDate");

                    b.Property<DateTime?>("DtStartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dtStartTime");

                    b.Property<int?>("IntCNCLatheMachine")
                        .HasColumnType("int")
                        .HasColumnName("intCNCLatheMachine");

                    b.Property<int?>("IntJobID")
                        .HasColumnType("int")
                        .HasColumnName("intJobID");

                    b.Property<int?>("IntLineID")
                        .HasColumnType("int")
                        .HasColumnName("intLineID");

                    b.Property<int?>("IntProductionQty")
                        .HasColumnType("int")
                        .HasColumnName("intProductionQty");

                    b.Property<int?>("IntUserID")
                        .HasColumnType("int")
                        .HasColumnName("intUserID");

                    b.Property<string>("StrLotInform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strLotInform");

                    b.Property<string>("StrMaterialInform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strMaterialInform");

                    b.Property<string>("StrNotes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strNotes");

                    b.HasKey("IntID");

                    b.ToTable("tbProductionData");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntLevel")
                        .HasColumnType("int")
                        .HasColumnName("intLevel");

                    b.Property<int>("IntRoleID")
                        .HasColumnType("int")
                        .HasColumnName("intRoleID");

                    b.Property<int?>("IntRoleUser")
                        .HasColumnType("int")
                        .HasColumnName("intRoleUser");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StrDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("strDescription");

                    b.Property<string>("StrRoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strRoleName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.Shift", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<TimeSpan?>("DtEndTime")
                        .HasColumnType("time")
                        .HasColumnName("dtEndTime");

                    b.Property<TimeSpan?>("DtStartTime")
                        .HasColumnType("time")
                        .HasColumnName("dtStartTime");

                    b.Property<string>("StrNameShift")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StrNameShift");

                    b.HasKey("IntID");

                    b.ToTable("tbShift");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.TVDisplay", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<string>("StrCavityID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strCavityID");

                    b.Property<string>("StrCharacteristicID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strCharacteristicID");

                    b.Property<string>("StrMoldID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strMoldID");

                    b.Property<string>("StrPlanTypeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strPlanTypeID");

                    b.Property<string>("StrProductionID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strProductionID");

                    b.Property<string>("StrTVName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strTVName");

                    b.HasKey("IntID");

                    b.ToTable("tbTVDisplay");
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DtLastActivityTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dtLastActivityTime");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("IntEnable")
                        .HasColumnType("int")
                        .HasColumnName("intEnable");

                    b.Property<int>("IntUserID")
                        .HasColumnType("int")
                        .HasColumnName("intUserID");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strDepartment");

                    b.Property<string>("StrEmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strEmailAddress");

                    b.Property<string>("StrFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strFullName");

                    b.Property<string>("StrPassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strPassword");

                    b.Property<string>("StrRoleID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strRoleID");

                    b.Property<string>("StrSelectedAreaID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strSelectedAreaID");

                    b.Property<string>("StrStaffID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strStaffID");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("YudaSPCWebApplication.BackendServer.Data.Entities.WebSession", b =>
                {
                    b.Property<int>("IntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntID"));

                    b.Property<DateTime?>("DtEndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dtEndTime");

                    b.Property<DateTime?>("DtStartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dtStartTime");

                    b.Property<string>("StrIpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strIpAddress");

                    b.Property<string>("StrSessionID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strSessionID");

                    b.HasKey("IntID");

                    b.ToTable("tbWebSession");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("YudaSPCWebApplication.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
